session_name: kivy
start_directory: ~/study/kivy
shell_command_before: VENV_NAME=kivy VENV_DIR=$HOME/.virtualenvs/$VENV_NAME VENV_ACTIVATE=$VENV_DIR/bin/activate; [ -d $VENV_DIR -a -f $VENV_ACTIVATE ] && source $VENV_ACTIVATE || virtualenv $VENV_DIR && source $VENV_ACTIVATE
windows:
- window_name: kivy
  options:
    main-pane-height: 35
  layout: main-horizontal
  start_directory: ~/study/kivy/kivy
  focus: true
  panes:
  - shell_command:
    - pane
    focus: true
  - pane
  - pane
- window_name: kivy-designer
  options:
    main-pane-height: 35
  layout: main-horizontal
  start_directory: ~/study/kivy/kivy-designer/
  panes:
  - shell_command:
    - pane
    focus: true
  - pane
  - pane
- window_name: python-for-android
  options:
    main-pane-height: 35
  layout: main-horizontal
  start_directory: ~/study/kivy/python-for-android/
  panes:
  - shell_command:
    - pane
    focus: true
  - pane
  - pane
- window_name: buildozer
  options:
    main-pane-height: 35
  layout: main-horizontal
  start_directory: ~/study/kivy/buildozer/
  panes:
  - shell_command:
    - pane
    focus: true
  - pane
  - pane
