session_name: pyterm
start_directory: ~/study/python/ # load session relative to config location (project root).
before_script: ~/.dot-config/.tmuxp/pyterm/bootstrap_env.py # ./ to load relative to project root.
windows:
- window_name: python-prompt-toolkit
  focus: True
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before:
    - '[ -d .venv -a -f .venv/bin/activate ] && source .venv/bin/activate'
  start_directory: python-prompt-toolkit/
  panes:
  - focus: true
  - pane 
  - pane 
- window_name: pyvim
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before:
    - '[ -d .venv -a -f .venv/bin/activate ] && source .venv/bin/activate'
  start_directory: pyvim/
  panes:
  - focus: true
  - pane 
  - pane 
- window_name: pymux
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before:
    - '[ -d .venv -a -f .venv/bin/activate ] && source .venv/bin/activate'
  start_directory: pymux/
  panes:
  - focus: true
  - pane 
  - pane 
- window_name: ptpdb
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before:
    - '[ -d .venv -a -f .venv/bin/activate ] && source .venv/bin/activate'
  start_directory: ptpdb/
  panes:
  - focus: true
  - pane 
  - pane 
- window_name: ptpython
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before:
    - '[ -d .venv -a -f .venv/bin/activate ] && source .venv/bin/activate'
  start_directory: ptpython/
  panes:
  - focus: true
  - pane 
  - pane 
- window_name: profiling
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before:
    - '[ -d .venv -a -f .venv/bin/activate ] && source .venv/bin/activate'
  start_directory: ~/work/python/profiling/
  panes:
  - focus: true
  - pane
  - pane
